### ISSUE TITLE
Create regular layout for story generator

### ISSUE THREAD

**Issue by gggodhwani** [cbgaindia/story-generator#1]

**Comment by noopurvarma** [comment]
Have a rough structure of layout that I am building up on. I will be spending time on it today. 
![1 layout_story_generator](https://cloud.githubusercontent.com/assets/4928010/14178169/13e56690-f777-11e5-8489-1d9b9de36e15.png)

**Comment by navsie** [comment]
Good start Noopur, thanks! Just few review points on the rough sketch. It may be early to comment on a rough sketch. Doing it just to ensure  it is taken care if considered valid -
1. In the "Select State" field, can we name them SELECT STATE 1 and SELECT STATE 2?
2. Should we mention some text like Compare preceeding The Select State fields?
3.The Search field text - Search Schemes or Ministries?
4. It's a question not a review - Introduction would contain?
5. Guess you are yet to include options for embed and share, so not commenting on that
6. Is the design done keeping mobile rendering as well?

**Comment by navsie** [comment]
Due by Thursday(07/04/2016) as per the discussion with @noopurvarma

**Comment by noopurvarma** [comment]
![01-dashboard](https://cloud.githubusercontent.com/assets/4928010/14587323/10c710e8-04cf-11e6-8332-610adca4b47f.png) Updated layout for story generator. 
Discussed the layout and components with @raeoks and @tejasrivastav. They can comment on the implementation and feasibility of things. 
PS: There is absolutely NO Visual Design done on this yet. I will be working on them today.

**Comment by tejasrivastav** [comment]
@noopurvarma can you share the font details

**Comment by noopurvarma** [comment]
Updated/alternative layout ![02-dashboard](https://cloud.githubusercontent.com/assets/4928010/14637678/82e177c2-0650-11e6-9bd5-fb00d8727920.png)

**Comment by noopurvarma** [comment]
Another version with minor changes in fonts and layout. ![Uploading 02-Dashboard.png…]()

**Comment by noopurvarma** [comment]
Design for layout is fixed, as after discussion with CBGA.
