### ISSUE TITLE
Refining work for Layout

### ISSUE THREAD

**Issue by navsie** [cbgaindia/story-generator#24]
1. Fix Typography
   - Right Fonts
     -Right Sizes

2.Detailing of Search States

**Comment by navsie** [comment]
**Priority 1**

**Comment by navsie** [comment]
Correct the font size as per  the Zeplin 
https://www.google.com/fonts/specimen/PT+Sans

**Comment by navsie** [comment]
@gggodhwani  Could you report the bugs you found here?

**Comment by tejasrivastav** [comment]
As informed @raeoks 
The fonts are loaded from
``` https://cbgaindia.github.io/fonts/PTSansWeb/stylesheet.css ```
but expected path is
``` https://cbgaindia.github.io/bat/fonts/PTSansWeb/stylesheet.css ```

i guess we might need to change the base path of production
