### ISSUE TITLE
Design for data viz section first draft

### ISSUE THREAD

**Issue by gggodhwani** [cbgaindia/story-generator#30]
- Work on the tooltip representation of the dataviz
-  Iteration of dataviz taking edge cases of the data (Maximum selection, maximum difference in the data)
- Improvise on the visual elements of the dataviz

**Comment by SuchismitaNaik** [comment]
![1_one_state](https://cloud.githubusercontent.com/assets/16536382/15849113/8798865a-2cae-11e6-8867-0740d0e52047.jpg)
![2_two_state](https://cloud.githubusercontent.com/assets/16536382/15849114/87a29ed8-2cae-11e6-815c-20fff2d632cc.jpg)
![3_on_hover](https://cloud.githubusercontent.com/assets/16536382/15849115/87a41970-2cae-11e6-8c4b-8707dfaccf81.jpg)
![4_be_selection](https://cloud.githubusercontent.com/assets/16536382/15849116/87a9ad86-2cae-11e6-9905-64a6178c5f16.jpg)

Visualisation of based on selection of state ( one or multiple ) and budget type (BE,RE, AC)

**Comment by navsie** [comment]
Thanks Suchi. Could you upload it in Zeplin as well and comment the link here?

**Comment by akshay2905** [comment]
Can I suggest a few issues with suggestions : 
Generic(for all visualization) Issues and suggestion -
1. Too much of gap between bar makes it difficult to compare the heights of the bar. 
2. Make Grid lines more visible. Difficult to figure the figures(height of rightmost bars).
3. Missing Axis line( X-Axis and Y-Axis )
4. Represent the side bar element which shows the state or the state comparison ( Bihar vs Karnataka ) can be moved below the heading. 
5. Tooltip Representation.

**Comment by gggodhwani** [comment]
@SuchismitaNaik Couple of suggestions from my end:
1) Axes: As @akshay2905 mentioned, both the axis will be quite important for our case
2) State Comparators: It would be better if we create a line graph with bullets for all comparisons done across states, I feel we should keep bars just for single state visualization. 
3) Color Pallet: Can we keep in non-gradient order, alternate light and dark would personally easy for me to concentrate on figures.
4) Tool-tips: We need to consider edge cases where tool-tips may have less vertical space given the height of the bars. Thus, I feel having low opacity background for tool-tip along with center aligned strong line with make more sense.
5) Grids: Currently grids are hardly visible, we might need to increase its opacity a bit more.
6) Legends: State legends would be slightly difficult for the multi-state selections because of space issues, we might need to get rid of it as we are already showing them on the map.
7) Label: We might need to give an appropriate label to x-axis, for e.g.: 'Budget Years' or 'Timeline' might make some sense. Also heading with names of states, could become sub-heading(with lower font size) so that you have good space to accommodate the max cap of 10 states.

**Comment by SuchismitaNaik** [comment]
![state1](https://cloud.githubusercontent.com/assets/16536382/16339801/43b28bb0-3a42-11e6-9dce-b7472c19faed.jpg)
![state2](https://cloud.githubusercontent.com/assets/16536382/16339802/43b29eb6-3a42-11e6-91a2-9213c583d520.jpg)
![state3](https://cloud.githubusercontent.com/assets/16536382/16339800/43b15506-3a42-11e6-9d2f-bb4128be6c66.jpg)
