### ISSUE TITLE
 Tooltip representation of the dataviz

### ISSUE THREAD

**Issue by navsie** [cbgaindia/story-generator#34]

**Comment by navsie** [comment]
Expected to have been completed by 20th June.

**Comment by SuchismitaNaik** [comment]
![state1](https://cloud.githubusercontent.com/assets/16536382/16336496/bb191172-3a2b-11e6-8d7e-938d71a191fe.jpg)
![state2](https://cloud.githubusercontent.com/assets/16536382/16336497/bb19d1f2-3a2b-11e6-9107-07dde14d74ac.jpg)
![state3](https://cloud.githubusercontent.com/assets/16536382/16336498/bb1c6a66-3a2b-11e6-8abf-12f06bbefc36.jpg)

**Comment by SuchismitaNaik** [comment]
![viz_state_2_tooltip](https://cloud.githubusercontent.com/assets/16536382/16706378/7c24383c-45c7-11e6-95fe-5dccecb841f7.png)
