### ISSUE TITLE
Design dataviz for multiple states selection for an indicator

### ISSUE THREAD

**Issue by navsie** [cbgaindia/story-generator#36]

**Comment by SuchismitaNaik** [comment]
These are the iterations for the one indicator + n state selection. 
Iterations are in terms of the use of the chart type and the tooltip representation for each. One is bar chart and other is line chart.

![indicator1_staten_1](https://cloud.githubusercontent.com/assets/16536382/16725907/320c61aa-4777-11e6-91c5-c697c2de23ec.jpg)
![indicator1_staten_2](https://cloud.githubusercontent.com/assets/16536382/16725906/32030f60-4777-11e6-97e7-67a365d85417.jpg)
![indicator1_staten_3](https://cloud.githubusercontent.com/assets/16536382/16725904/320119a8-4777-11e6-8913-5aa3de1c3c4c.jpg)
![indicator1_staten_4](https://cloud.githubusercontent.com/assets/16536382/16725905/32029a08-4777-11e6-8e9f-ca047c068bf5.jpg)

**Comment by SuchismitaNaik** [comment]
These are the variation in the legend style.

![indicator1_staten_5](https://cloud.githubusercontent.com/assets/16536382/16727801/840a7542-4780-11e6-84fe-3c26f8679850.jpg)
![indicator1_staten_6](https://cloud.githubusercontent.com/assets/16536382/16727802/840b85d6-4780-11e6-9a82-ed9a8e5d6659.jpg)

If the side bar is collapsable. Then Map based viz can be integrated.

![indicator1_staten_7](https://cloud.githubusercontent.com/assets/16536382/16727800/840a16ec-4780-11e6-9d4f-90f576b7acb7.jpg)

On hovering on each state

![indicator1_staten_8](https://cloud.githubusercontent.com/assets/16536382/16727799/84092bec-4780-11e6-8aa4-308a513f1fc7.jpg)

**Comment by SuchismitaNaik** [comment]
Negative, Positive and zero values

![iteration_positive_negative](https://cloud.githubusercontent.com/assets/16536382/17083081/9188d462-51b1-11e6-9b1e-b0a337a32372.jpg)

**Comment by SuchismitaNaik** [comment]
Negative, positive and zero values in bar chart

![positive_negative_bar_chart](https://cloud.githubusercontent.com/assets/16536382/17399257/a89dd3ea-5a5e-11e6-90fb-06441edfcbb0.jpg)
