### ISSUE TITLE
Brainstorm on Landing Viz (Noopur)

### ISSUE THREAD

**Issue by navsie** [cbgaindia/story-generator#37]

**Comment by SuchismitaNaik** [comment]
Landing visualisation iterations

![landing_viz2](https://cloud.githubusercontent.com/assets/16536382/17461217/a054eaac-5ca2-11e6-9944-4dc2b1e173d8.jpg)
![landing_viz1](https://cloud.githubusercontent.com/assets/16536382/17461218/a059a83a-5ca2-11e6-8e87-9431cc1cf859.jpg)
