### ISSUE TITLE
Time slider for graph

### ISSUE THREAD

**Issue by gggodhwani** [cbgaindia/story-generator#4]

**Comment by navsie** [comment]
Due by Thursday(07/04/2016) as per the discussion with @noopurvarma

**Comment by noopurvarma** [comment]
@gggodhwani Time slider should be a part for iteration 1, when we do the visualization part.

**Comment by gggodhwani** [comment]
@noopurvarma Can we pick it up in Iteration 2?

**Comment by noopurvarma** [comment]
@gggodhwani Yes. It makes sense to do that, since it's very closely coupled with the visualization.

**Comment by navsie** [comment]
Assigning it to @SuchismitaNaik as she is working on the design of Data Viz area. Milestone not set yet as we did not discuss this for this iteration.
