### ISSUE TITLE
De-selection of states

### ISSUE THREAD

**Issue by navsie** [cbgaindia/story-generator#41]
@tejasrivastav  Could you better describe the task?

**Comment by tejasrivastav** [comment]
As of now once the states are selected we don't support undoing of the same.
This task to implement the state deselection after it selection.

**Comment by tejasrivastav** [comment]
Have implemented the UI.
But on removal of the state the url need to change.
Currently the state is removed from the UI, but not from the UI.
@raeoks couldn't figure it out.
Can you help me with it?
