### ISSUE TITLE
UI freezes as we try to select an Indicator after max states selection for previous indicator

### ISSUE THREAD

**Issue by gggodhwani** [cbgaindia/story-generator#45]
![hung_up](https://cloud.githubusercontent.com/assets/2306011/16979234/9acd20e6-4e7d-11e6-9943-6341622aaaa4.png)

@raeoks I guess you are working to make sure select (de)selection transitions are smooth without hiccups.
@tejasrivastav  Can you relook and check if its a UI bug?

**Comment by gggodhwani** [comment]
Moreover deselection doesn't seem to work!

**Comment by archetana** [comment]
Issue is fixed
