### ISSUE TITLE
Values in the graph don't change after two states selection

### ISSUE THREAD

**Issue by gggodhwani** [cbgaindia/story-generator#50]
One sees same values being repeated for 2+ state selection for all indicators, for e.g.:

![story-gen](https://cloud.githubusercontent.com/assets/2306011/17339263/bcb0fd5a-5908-11e6-8901-c3d527ece141.png)

**Comment by archetana** [comment]
The issue was with the json data, where all the values after first state (MP) were the same, made changes to indicator_amounts_row.js. The issue is fixed
