### ISSUE TITLE
Metadata Format

### ISSUE THREAD

**Issue by navsie** [cbgaindia/story-generator#51]

**Comment by gggodhwani** [comment]
@navsie @tejasrivastav @archetana @raeoks CBGA team has come up with the basic in-progress metadata sheet. Please have a look: https://docs.google.com/spreadsheets/d/156hz_VTfrNzqkHxzm5LbRH-o5TgbUxm-bVFXn0EZSdk/edit?usp=sharing 

If we need any changes in the format then let us know.

**Comment by navsie** [comment]
CBGA team has come up with the basic in-progress metadata sheet. Please have a look: https://docs.google.com/spreadsheets/d/156hz_VTfrNzqkHxzm5LbRH-o5TgbUxm-bVFXn0EZSdk/edit?usp=sharing
T:Indicator names for states are not same 
G: Make sure they would take care and are primary key 
If its a bottle-neck for searching then create individual keys 
Follow up with Rohit 

Source - assumption was link but it’s a text given in the metadata format
Add another box like desc,  notes
