### ISSUE TITLE
Iteration on Map visualisation (Landing visualisation)

### ISSUE THREAD

**Issue by SuchismitaNaik** [cbgaindia/story-generator#56]

**Comment by SuchismitaNaik** [comment]
![map_viz_1](https://cloud.githubusercontent.com/assets/16536382/18413530/17758656-77c8-11e6-9f35-4f62317a462e.jpg)

**Comment by SuchismitaNaik** [comment]
Iterations on the landing visualisation. 

![landing_viz2_1](https://cloud.githubusercontent.com/assets/16536382/19159538/815e5812-8c0a-11e6-845b-dbc1a0136781.jpg)
![landing_viz2_2](https://cloud.githubusercontent.com/assets/16536382/19159539/8162712c-8c0a-11e6-805d-12461bdb9565.jpg)
![landing_viz2_3](https://cloud.githubusercontent.com/assets/16536382/19159537/8155576c-8c0a-11e6-9b3a-7bd53954c485.jpg)

**Comment by SuchismitaNaik** [comment]
Added button of toggle on the top. Moved the budget attributes to the right section.
![2](https://cloud.githubusercontent.com/assets/16536382/20020619/2e52937c-a2f8-11e6-8ccf-828b8540df18.jpg)
![3](https://cloud.githubusercontent.com/assets/16536382/20020620/2e5298d6-a2f8-11e6-9649-725de8ebf283.jpg)
![4](https://cloud.githubusercontent.com/assets/16536382/20020618/2e4a002c-a2f8-11e6-8f26-b71a9722af0a.jpg)

Taskflow from the landing visualisation.
![taskflow](https://cloud.githubusercontent.com/assets/16536382/20020838/3b42f512-a2f9-11e6-8292-66ca9e70d828.gif)

**Comment by SuchismitaNaik** [comment]
Landing Visualisation screen 
![1](https://cloud.githubusercontent.com/assets/16536382/20027969/5f47561e-a34a-11e6-80a3-53e1e92391a5.jpg)

**Comment by tejasrivastav** [comment]
@SuchismitaNaik  @gggodhwani 
With respect to updated viz 
how should the embed behaviour work?
