### ISSUE TITLE
Can't run npm install because of react version mismatch

### ISSUE THREAD

**Issue by apoorv-kumar** [cbgaindia/story-generator#76]
When I npm install the project, I see the following error - 

> npm ERR! node v4.4.3
> npm ERR! npm  v2.15.1
> npm ERR! code EPEERINVALID
> 
> npm ERR! peerinvalid The package react@15.0.2 does not satisfy its siblings' peerDependencies requirements!
> npm ERR! peerinvalid Peer react-bootstrap@0.30.10 wants react@>=0.14.0
> npm ERR! peerinvalid Peer react-d3-basic@1.6.11 wants react@^0.14.7
> npm ERR! peerinvalid Peer react-dom@15.0.2 wants react@^15.0.2
> npm ERR! peerinvalid Peer react-leaflet@1.1.4 wants react@^15.0.0
> npm ERR! peerinvalid Peer react-redux@4.4.5 wants react@^0.14.0 || ^15.0.0-0
> npm ERR! peerinvalid Peer react-router@2.4.0 wants react@^0.14.0 || ^15.0.0
> npm ERR! peerinvalid Peer react-select@1.0.0-rc.5 wants react@^0.14 || ^15.0.0-rc || ^15.0
> npm ERR! peerinvalid Peer react-vis@1.6.7 wants react@0.14.x - 15.x
> npm ERR! peerinvalid Peer react-addons-test-utils@15.0.2 wants react@^15.0.2
> npm ERR! peerinvalid Peer enzyme@2.2.0 wants react@0.13.x || 0.14.x || 15.* || ^15.0.0-rc
> 

It sees no single version of react satisfies all dependencies. Anyone else facing this issue ?

**Comment by akshay2905** [comment]
Hey @apoorv-kumar, there might be another issue related to npm. Can you try to update the npm packages as there might be dependencies on other modules that are available globally but are older. 
Try executing the following command -  
`npm update -g`

**Comment by apoorv-kumar** [comment]
That worked! Thanks, Closing the issue.
